---
title: "mariama"
author: "Mariama Jaiteh, Fiona Miller, Starry Zhou"
date: "4/26/2017"
output: html_document
---
```{r}
#Load Libraries!
library(sp)
library(macleish)
library(tidyverse)
library(rgeos)
library(rgdal)
library(dplyr)

```
# 10’ contour elevation data
```{r}
# Download terrain data for Whatley
url <- "http://wsgw.mass.gov/data/gispub/shape/contours5k/hp337.zip"
download.file(url, destfile = basename(url))
unzip("hp337.zip", exdir = "whately_contours")

# Load and transform
whately_GIS_data <- path.expand("whately_contours")
whately_contours <- readOGR(whately_GIS_data, "hp337") %>%
  spTransform(CRS("+init=epsg:4326"))

```

```{r}
# Download terrain data for Conway
url <- "http://wsgw.mass.gov/data/gispub/shape/contours5k/hp68.zip"
download.file(url, destfile = basename(url))
unzip("hp68.zip", exdir = "conway_contours")

# Load and transform
conway_GIS_data <- path.expand("conway_contours")
conway_contours <- readOGR(conway_GIS_data, "hp68") %>%
  spTransform(CRS("+init=epsg:4326"))
```

```{r}
macleish_contours <-
  gUnion(conway_contours, whately_contours) %>%
  gIntersection(macleish_layers[['boundary']])
remove(whately_contours, conway_contours)

```

```{r}
# What happens when you intersect lines?
trail_points <- macleish_contours %>%
  gIntersection(macleish_layers[['trails']])
```

# Campsites
```{r}
sites = data.frame( name = c("Group Campsite","Remote Campsite","Parking"), lat = c(42.450976,42.458570,42.448013),long = c(-72.678154,-72.674732,-72.680663))
```

# Buffer
```{r}
## Buffer for stream (200 ft)
proj4_aea <- "+proj=aea +lat_1=29.5 +lat_2=42.5 +lat_0=37.5 +lon_0=-96 +x_0=0 +y_0=0 +ellps=GRS80 +datum=NAD83 +units=m +no_defs"
stream <- macleish_layers[["streams"]] %>%
  spTransform(CRS(proj4_aea)) %>%
  gBuffer(width = 60.96) %>%
  spTransform("+init=epsg:4326")

```

```{r}
## Buffer on Challenge courses (500 ft)
challenge <- macleish_layers[["challenge_courses"]] %>%
  spTransform(CRS(proj4_aea)) %>%
  gBuffer(width = 152.4) %>%
  spTransform("+init=epsg:4326")
```

```{r}
## Buffer on research projects (500ft)
research <- macleish_layers[["research"]] %>%
  spTransform(CRS(proj4_aea)) %>%
  gBuffer(width = 152.4) %>%
  spTransform("+init=epsg:4326")
```

```{r}
boundaries_aea <- macleish_layers[["boundary"]] %>%
  spTransform(CRS(proj4_aea))
```

# plot
```{r}
#Plotting the streams --not needed after everything is finished.
library(leaflet)
leaflet() %>%
  addTiles() %>%
  addPolylines(data = macleish_layers[["streams"]], 
               weight = 1, color = "black") %>%
  addPolygons(data = stream) 

```

```{r}
## Use as a reference for Forest type.
leaflet() %>%
  addTiles() %>%
  addPolygons(data = macleish_layers[["buildings"]], 
              weight = 1, popup = ~ name) %>%
  addPolygons(data = macleish_layers[["forests"]], 
              weight = 1, fillOpacity = 0.2, popup = ~ Sheet1__Na) %>%
  addMarkers(lng = ~long, lat = ~lat, data = sites,
    popup = ~name) %>%
  addPolygons(data = challenge) 

```

```{r}
## blue, black and white
leaflet() %>%
  addTiles() %>%
  addPolygons(data = macleish_layers[["buildings"]], 
              weight = 1, popup = ~ name, color = "brown") %>%
  addPolygons(data = macleish_layers[["forests"]], 
              leaflet()%>%
                weight = 1, fillOpacity = 0.2, popup = ~ Sheet1__Na, color = "green") %>%
  addMarkers(lng = ~long, lat = ~lat, data = sites,
    popup = ~name)  %>%
  addPolygons(data = stream, color = "blue") %>%
  addPolygons(data = research, color = "purple") %>%
  addPolygons(data = macleish_layers[["boundary"]], color = "black") %>%
  addPolygons(data = challenge, color = "yellow") %>%
  addCircles(lat = 42.448013, lng = -72.680663, radius = 804.672,color="white") %>%
  addPolylines(data = macleish_contours, weight = 1, color = "black") %>%
  addPolylines(data = macleish_layers[["trails"]], weight = 3, color = "red") %>%
  addCircleMarkers(data = trail_points, radius = 2, color = "red") 
```
## rightest, vermal pool sedge meadow
```{r}
leaflet() %>%
  addTiles() %>%
    addMarkers(lng = ~long, lat = ~lat, data = sites,
    popup = ~name) %>%
  addPolygons(data = macleish_layers[["forests"]], 
              weight = 1, fillOpacity = 0.2, popup = ~ Sheet1__Na, color = "green") 
```
In white radius blue stream and black boundary. Not in brown buildings, purple research, yellow challenge courses. In all forest except the two forest types of the other two campsites

```{r}
forestnames<-as.data.frame(macleish_layers[["forests"]]$Sheet1__Na)
vernal<-forestnames%>% 
  filter(macleish_layers[["forests"]]$Sheet1__Na=="Vernal Pool Sedge Meadow")
vernal
```

```{r}
leaflet() %>%
  addTiles() %>%
    addMarkers(lng = ~long, lat = ~lat, data = sites,
    popup = ~name)%>%
addMarkers(lat = 42.454773,lng=-72.6776975)
```